#!/usr/bin/env node
// scripts/gates/content-status.ts — `npm run content:status` rebuilds `work/04-app/ledger.generated.md`
// from every module.yaml's own `status` field (plan §4.6.2: "planned -> drafted -> gated ->
// reviewed -> accepted... npm run content:status writes work/NN/ledger.generated.md"). Read-only
// over content/ (+ tests/fixtures/content/); this is the one file under work/04-app/ that this
// script, and only this script, ever writes — never hand-edit it (plan CLAUDE.md: "never manually
// modify... any files that are marked as auto-generated").

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "yaml";
import { courseSchema, moduleFileSchema } from "@/lib/content/schemas";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const APP_ROOT = path.resolve(HERE, "..", "..");
const REPO_ROOT = path.resolve(APP_ROOT, "..");
const REAL_ROOT = path.join(APP_ROOT, "content");
const FIXTURE_ROOT = path.join(APP_ROOT, "tests", "fixtures", "content");
const LEDGER = path.join(REPO_ROOT, "work", "04-app", "ledger.generated.md");

interface Row {
  stageId: string;
  stageTitle: string;
  moduleId: string;
  courseTitle: string;
  status: string;
  authored: boolean;
}

function readCourse(root: string) {
  const file = path.join(root, "course.yaml");
  if (!fs.existsSync(file)) return [];
  return courseSchema.parse(parse(fs.readFileSync(file, "utf8"))).stages;
}

function findModuleYaml(root: string, stageId: string, moduleId: string): string | null {
  const stagesDir = path.join(root, "stages");
  if (!fs.existsSync(stagesDir)) return null;
  for (const stageDir of fs.readdirSync(stagesDir, { withFileTypes: true })) {
    if (!stageDir.isDirectory() || !stageDir.name.startsWith(`${stageId}-`)) continue;
    const stagePath = path.join(stagesDir, stageDir.name);
    for (const moduleDir of fs.readdirSync(stagePath, { withFileTypes: true })) {
      if (!moduleDir.isDirectory() || !moduleDir.name.startsWith(`${moduleId}-`)) continue;
      const file = path.join(stagePath, moduleDir.name, "module.yaml");
      if (fs.existsSync(file)) return file;
    }
  }
  return null;
}

function buildRows(root: string): Row[] {
  const rows: Row[] = [];
  for (const stage of readCourse(root)) {
    for (const m of stage.modules) {
      const moduleYamlFile = findModuleYaml(root, stage.id, m.id);
      let status = m.status;
      let authored = false;
      if (moduleYamlFile) {
        const data = moduleFileSchema.parse(parse(fs.readFileSync(moduleYamlFile, "utf8")));
        status = data.status;
        authored = true;
      }
      rows.push({
        stageId: stage.id,
        stageTitle: stage.title,
        moduleId: m.id,
        courseTitle: m.title,
        status,
        authored,
      });
    }
  }
  return rows;
}

function main() {
  const rows = [...buildRows(REAL_ROOT), ...buildRows(FIXTURE_ROOT)];

  const counts = new Map<string, number>();
  for (const r of rows) counts.set(r.status, (counts.get(r.status) ?? 0) + 1);

  const lines: string[] = [
    "<!-- AUTO-GENERATED by `npm run content:status` (main-app/scripts/gates/content-status.ts). Never hand-edit. -->",
    "# Content ledger",
    "",
    `Generated: ${new Date().toISOString()}`,
    "",
    "## Summary",
    "",
    "| status | count |",
    "|---|---|",
    ...["planned", "drafted", "gated", "reviewed", "accepted"].map(
      (s) => `| ${s} | ${counts.get(s) ?? 0} |`,
    ),
    `| **total** | **${rows.length}** |`,
    "",
    "## By stage",
    "",
  ];

  let currentStage: string | null = null;
  for (const r of rows) {
    if (r.stageId !== currentStage) {
      currentStage = r.stageId;
      lines.push(
        `### ${r.stageId} — ${r.stageTitle}`,
        "",
        "| module | title | status | authored |",
        "|---|---|---|---|",
      );
    }
    lines.push(`| ${r.moduleId} | ${r.courseTitle} | ${r.status} | ${r.authored ? "yes" : "no"} |`);
  }
  lines.push("");

  fs.mkdirSync(path.dirname(LEDGER), { recursive: true });
  fs.writeFileSync(LEDGER, `${lines.join("\n")}\n`, "utf8");
  console.log(`Wrote ${path.relative(REPO_ROOT, LEDGER)} (${rows.length} modules).`);
}

main();
